fix(pipeline): corrigido erros na pipeline
Signed-off-by: Kalil Teixeira Ventura Monteiro <kalilventur@gmail.com>

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,92 +1,111 @@
-name: pipeline
+name: Build, Test and Deploy to Docker Hub
 
 on:
   push:
+    branches:
+      - master  # or your default branch
+    tags:
+      - '*'
+  pull_request:
+    branches:
+      - 'master'
+  workflow_dispatch:
 
 jobs:
-  unit-test:
+  tests_test-all:
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-        
-    - run: mvn test  
-    
-    - name: Generate JaCoCo Badge
-      id: jacoco
-      uses: cicirello/jacoco-badge-generator@v2.0.1
-    - name: Log coverage percentage
-      run: |
-        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
-        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"    
-    
-    - name: Upload JaCoCo coverage report
-      uses: actions/upload-artifact@v2
-      with:
-        name: jacoco-report
-        path: target/site/jacoco/
-        
-  code-analisys:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'corretto'
+
+      - name: Cache Maven packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Run Tests
+        run: mvn test
+
+  quality_sonarqube-analysis:
+    name: 'quality > sonarqube-analysis'
     runs-on: ubuntu-latest
-    needs: unit-test
-    
+    needs: [tests_test-all]
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Set up JDK 17
-      uses: actions/setup-java@v1
-      with:
-        java-version: 11    
-    - name: Cache SonarCloud packages
-      uses: actions/cache@v1
-      with:
-        path: ~/.sonar/cache
-        key: ${{ runner.os }}-sonar
-        restore-keys: ${{ runner.os }}-sonar
-        
-    - name: Build and analyze
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'corretto'
+      - name: Cache SonarQube packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+      - name: Build and analyze
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SOAT-46_ms-video-crud
 
-      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Devops-Fiap
-    
-  build:
-    name: Build Archive
+  docker_build-and-push:
+    name: 'docker > build and push'
     runs-on: ubuntu-latest
-    needs: unit-test #code-analisys
-    
+    needs: [tests_test-all]
+    if: github.event_name != 'pull_request'
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Build with Maven
-      run: mvn -B package -DskipTests --file pom.xml      
-    - name: Display structure of downloaded files
-      run: ls -R
-      working-directory: target/
-    - name: Upload JAR
-        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
-      uses: actions/upload-artifact@v2
-      with:
-        #Set artifact name
-        name: artifact
-        #From this path
-        path: ./target/demo-0.0.2.7-SNAPSHOT.jar 
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-  deploy-prod:
-    runs-on: ubuntu-latest
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    if: github.ref == 'refs/heads/main'
-    environment:
-      name: prod
-    needs: build
-
-    steps:
-      - name: Deploy 
-        shell: bash
+      - name: Validate Docker Hub repository
+        id: validate-repo
         run: |
-          echo "Deploy PROD"
+          REPO_NAME="ms-video"
+          NAMESPACE="${{ secrets.DOCKER_USERNAME }}"
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${NAMESPACE}/${REPO_NAME}/")
+
+          if [ "$RESPONSE" -eq 200 ]; then
+            echo "Repository ${NAMESPACE}/${REPO_NAME} exists."
+          elif [ "$RESPONSE" -eq 404 ]; then
+            echo "Repository ${NAMESPACE}/${REPO_NAME} does not exist."
+            exit 1
+          else
+            echo "Failed to check repository existence. HTTP status code: ${RESPONSE}"
+            exit 1
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ secrets.DOCKER_USERNAME }}/ms-video:latest
+            ${{ secrets.DOCKER_USERNAME }}/ms-video:${{ github.sha }}
